url: https://phd.fbk.eu
#baseurl: /

# Site settings
title: Become a PhD student at FBK 
email: napo@fbk.eu
description: "FBK-ICT offers a unique stimulating and exciting environment to its PhD students. PhD students supervised by FBK-ICT researchers conduct their work in the lab of the research units, in strict collaboration with the units’ teams and under the supervision of top-ranked researchers, targeting the highest scientific and publication standards."

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
encoding: utf-8
